# # Create the ci part of the frontend. The cd part is done by netlify.
# # First we checkout of the repo, then we install dependencies and finally we build and test our code
# # Further explanation for the functions used here in the README.md file!!!
# name: CI

# on:
#   push:
#   pull_request:
#     branches:
#       - main

# jobs:
#   ci:
#     runs-on: ubuntu-latest
#     steps:
#       # Checkouts out of the repo
#       - name: Checkout repo
#         uses: actions/checkout@v3
          
#       # Install the dependencies  
#       - name: Install dependencies
#         run: npm install
        
      # # Tests on cypress
      # - name: Run test script
      #   uses: cypress-io/github-action@v4
      #   with:
      #     build: npm run build2
      #     start: npm run dev
      #     command: npm run test:ci
      #     install-command: npm ci --force
       
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
# name: Cypress Test

# on: [push]

# jobs:
#   cypress:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14'
#     - name: Install Dependencies
#       run: npm install
#     - name: Run Cypress Tests
#       run: npm run cypress:run

name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build and start server
        run: |
          npm run build2 -- --homepage http://localhost:3002/
          npm run dev -- --homepage http://localhost:3002/ &
      - name: Wait for server to start
        run: npx wait-on http://localhost:3002

      - name: Run Cypress tests
        run: npm run cypress:run