# Create the ci part of the frontend. The cd part is done by netlify.
# First we checkout of the repo, then we install dependencies and finally we build and test our code
# Further explanation for the functions used here in the README.md file!!!
name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Checkouts out of the repo
      - name: Checkout repo
        uses: actions/checkout@v3
          
      # Install the dependencies  
      - name: Install dependencies
        run: npm install
        
      # Tests on cypress
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Start server
        run: npm run start &

      - name: Wait for server to start
        run: sleep 10s

      - name: Run tests
        uses: cypress-io/github-action@v4
        with:
          command: npm test
          install-command: npm ci
