name: CICD

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Checkouts out of the repo
      - name: Checkout repo
        uses: actions/checkout@v3
            
      # Install the dependencies  
      - name: Install dependencies
        run: npm install
        
      # Tests on cypress
      - name: Run test script
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run preview
          command: npm run test:ci
          install-command: npm ci --force
       
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
  cd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: ci
    steps:      
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH.PORT }}
          script: |
            cd ~/se2/1/se2-frontend
            git reset --hard origin/main
            git pull https://${{ secrets.CLONE_TOKEN }}@github.com/karanikiotis/se2-frontend-1 main
            bash -ci 'npm i'
            bash -ci 'npm run build'
            bash -ci 'pm2 restart se2-frontend-1'
            