name: Revert main branch on push

on:
  push:
    branches:
      - main


jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Revert main branch
        run: |
          git reset -hard HEAD~1
          git push -f
          
# name: push
       
# on: push

# jobs:
#   ci:
#     runs-on: ubuntu-latest
#     steps:
#       # Don't allow the user to push on main directly
#       - name: Refuse push to main
#         run: |
#           if [ "$GITHUB_REF" == "refs/heads/main" ]; then
#             echo "User is not allowed to push to main branch"
#             exit 1
#           fi
        
#       # Checkouts out of the repo
#       - name: Checkout repo
#         uses: actions/checkout@v3
            
#       # Install the dependencies  
#       - name: Install dependencies
#         run: npm install
        
#       # Tests on cypress
#       - name: Run test script
#         uses: cypress-io/github-action@v4
#         with:
#           build: npm run build
#           start: npm run preview
#           command: npm run test:ci
#           install-command: npm ci --force
       
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
