name: Revert main branch on push

on:
  push:
    branches:
      - main

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Revert main branch
        run: |
            git fetch
            git reset --hard 6271ab5
            git push -f  





# name: Revert main branch on push

# on:
#   push:
#     branches:
#       - main

# jobs:
#   revert:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
      
#       - name: Fetch list of commits on main branch
#         run: |
#           git fetch
#           git rev-list --max-count=2 main > commits.txt
#           head -n 1 commits.txt > previous_commit.txt
#           tail -n 1 commits.txt > current_commit.txt
#         shell: bash
      
#       - name: Revert main branch to previous commit
#         run: |
#           git reset --hard $(cat previous_commit.txt)
#           git push -f
#         shell: bash


          
# name: push
       
# on: push

# jobs:
#   ci:
#     runs-on: ubuntu-latest
#     steps:
#       # Don't allow the user to push on main directly
#       - name: Refuse push to main
#         run: |
#           if [ "$GITHUB_REF" == "refs/heads/main" ]; then
#             echo "User is not allowed to push to main branch"
#             exit 1
#           fi
        
#       # Checkouts out of the repo
#       - name: Checkout repo
#         uses: actions/checkout@v3
            
#       # Install the dependencies  
#       - name: Install dependencies
#         run: npm install
        
#       # Tests on cypress
#       - name: Run test script
#         uses: cypress-io/github-action@v4
#         with:
#           build: npm run build
#           start: npm run preview
#           command: npm run test:ci
#           install-command: npm ci --force
       
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
