name: Revert main branch on push

on:
  push:
    branches:
      - main


jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Revert main branch
        run: |
          git reset --hard HEAD~1
          git push -f
